Limit scikit-learn versions between 0.22.2 and 1.1.3, remove deprecated load_boston().
Version limitation fixes the error: "TypeError: wrapped() missing 1 required positional argument: 'X'"
that is shown because of an API change in scikit-learn.

Signed-off-by: Maya Anderson <mayaa@il.ibm.com>